### ISSUE TITLE
Reference format

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posterior_database#10]
Currently references in the info files are in a format like this

```json
"references": ["Rubin (1981)", "Gelman et. al. (2014)"]
```

This format can be ambigious, for example if there are two papers published by Rubin in 1981. 

Should we include the paper title too? Or should we use a full bibtex entry?

**Comment by MansMeg** [comment]
We should use a full bibtex entry.

**Comment by MansMeg** [comment]
But these full bibtext-entries should probably be stored in an ordinary bibtex file and the referenceses should be for the bibtex items.

**Comment by MansMeg** [comment]
Fixed with 5ee9fb80d33a824bbab747db24255de8ac3a19c7

**Comment by eerolinna** [comment]
Good idea! That feels like the best solution to me too.
