### ISSUE TITLE
Model info files for models in many frameworks

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posterior_database#3]
Currently model infos are found by replacing the model file extension with `.info.json`. See for example [`content/models/8_schools/8_schools_centered.stan`](https://github.com/MansMeg/posterior_database/blob/master/content/models/8_schools/8_schools_centered.stan) and [`content/models/8_schools/8_schools_centered.info.json`](https://github.com/MansMeg/posterior_database/blob/master/content/models/8_schools/8_schools_centered.info.json)

What if we have models also in other frameworks like `PyMC` and `Pyro`? Then we might have the model files `8_schools_centered_pymc.py` and `8_schools_centered_pyro.py` (directories omitted). Do we also need `8_schools_centered_pymc.info.json`and `8_schools_centered_pyro.info.json`? Or can we have just one info file that describes the models of all frameworks?

**Comment by MansMeg** [comment]
I think we should have one model infor since there is one specific model that we represent. Then the different PPF have there own implementations of it.

**Comment by eerolinna** [comment]
I agree

**Comment by MansMeg** [comment]
Ok. I added a little info about this in design decision.
