### ISSUE TITLE
Rename stan_data_file_path

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posterior_database#4]
Should we just have `data_file_path` instead of `stan_data_file_path`? As datasets are probably not going to be framework specific.

**Comment by MansMeg** [comment]
Yes. I think Ill do so that I add the function data_file_path as a more generic solution but keep stan_data_file_path for situations when people use stan.

**Comment by eerolinna** [comment]
Hmm, would we ever have the situation where two frameworks have different data files? So that `stan_data_file_path(po)` and `pymc_data_file_path(po)` would return different results?

Or would it be that `stan_data_file_path` is just an alias for `data_file_path` and always returns the same result?

**Comment by MansMeg** [comment]
I'm not sure. But it may be so that we would need different datasets for different PPFs. As for now, I'll add the data_file_path and then we can see how it develops.

**Comment by MansMeg** [comment]
Now fixed

**Comment by eerolinna** [comment]
Should we also change the example in README to use `data_file_path`?

Personally I think it would be best to remove `stan_data_file_path` unless we can come up with a concrete situation where two PPFs would need different datasets. I feel it would make the API clearer. 

If at some point we end up needing two different data files we can change `data_file_path(po)` to `data_file_path(po, framework = "stan")` where "stan" is the default value for the framework optional argument. This change would maintain backward compatability.

**Comment by MansMeg** [comment]
Yep. Now fixed.
```
> sdfp <- data_file_path(po)
> sdfp
```
