### ISSUE TITLE
Add code_file_path

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posterior_database#5]
Currently we have `stan_code_file_path(po)`. I guess we should also have `code_file_path(po, framework = "stan/pymc/something else")` to make it possible to use models of other frameworks. Then `stan_code_file_path(po)` could be defined as `code_file_path(po, framework = "stan")`

**Comment by MansMeg** [comment]
Yes. That is a good idea!

**Comment by MansMeg** [comment]
Alright. this has now been fixed. I call it `model_code_file_path(po)` but else it looks the same.
