### ISSUE TITLE
Consider using a different separator than "|" for posterior names

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posterior_database#7]
Browsing the posterior database directory with the command line shell is a bit inconvenient because `|` is a special character in the shell. This is not a dealbreaker though.

**Comment by MansMeg** [comment]
Ok. is there any other character that would work better?

**Comment by eerolinna** [comment]
I can't think of any good single character. `&` is also a special character. We could use a sequence though, something like `--` or `__` or `___`. Or we can just keep `|` and accept the minor annoyance of browsing the posterior database directory from command line.

**Comment by MansMeg** [comment]
Ok. Lets keep |.
